Anonymous users never match user conditions
AnonymousUser does not always have the USERNAME_FIELD attribute (for
example it does not have an "email" field).

This fixes the following stacktrace:

```
  File "/usr/local/lib/python3.10/site-packages/flags/state.py", line 66, in flag_enabled
    return flag_state(flag_name, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/flags/state.py", line 61, in flag_state
    return _get_flag_state(flag_name, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/flags/state.py", line 13, in _get_flag_state
    return flag.check_state(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/flags/sources.py", line 51, in check_state
    checked_conditions = [(c, c.check(**kwargs)) for c in self.conditions]
  File "/usr/local/lib/python3.10/site-packages/flags/sources.py", line 51, in <listcomp>
    checked_conditions = [(c, c.check(**kwargs)) for c in self.conditions]
  File "/usr/local/lib/python3.10/site-packages/flags/sources.py", line 27, in check
    return self.fn(self.value, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/flags/conditions/conditions.py", line 36, in user_condition
    return getattr(request.user, get_user_model().USERNAME_FIELD) == username
  File "/usr/local/lib/python3.10/site-packages/django/utils/functional.py", line 249, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'email'
```